"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var gameboard_1 = require("./gameboard");
var troops_1 = require("./troops");
var util_1 = require("./util");
var board = new gameboard_1.GameBoard();
var solder = new troops_1.Solder();
board.insertTroop(solder, { x: 0, y: 0 });
var archer = new troops_1.Archer();
board.insertTroop(archer, { x: 3, y: 0 });
console.log(util_1.printBoard(board.create2dBoard()));
console.log('move soldier down:');
board.moveTroop(solder, { x: 0, y: 1 });
console.log(util_1.printBoard(board.create2dBoard()));
console.log('archer attacks soldier:');
board.attack(archer, archer.weapons[0], solder);
console.log(util_1.printBoard(board.create2dBoard()));
console.log('archer attacks soldier until he dies:');
board.attack(archer, archer.weapons[0], solder);
board.attack(archer, archer.weapons[0], solder);
board.attack(archer, archer.weapons[0], solder);
board.attack(archer, archer.weapons[0], solder);
board.attack(archer, archer.weapons[0], solder);
console.log(util_1.printBoard(board.create2dBoard()));
console.log('drop in the knight:');
var knight = new troops_1.Knight();
board.insertTroop(knight, { x: 9, y: 9 });
console.log(util_1.printBoard(board.create2dBoard()));
console.log('move knight 3 fields to the left:');
board.moveTroop(knight, { x: 6, y: 9 });
console.log(util_1.printBoard(board.create2dBoard()));
